; intial consonants
	const_def 1
	const INITIAL_GIYEOK
	const INITIAL_SSANGGIYEOK
	const INITIAL_NIEUN
	const INITIAL_DIGEUT
	const INITIAL_SSANGDIGEUT
	const INITIAL_RIEUL
	const INITIAL_MIEUM
	const INITIAL_BIEUP
	const INITIAL_SSANGBIEUP
	const INITIAL_SIOT
	const INITIAL_SSANGSIOT
	const INITIAL_IEUNG
	const INITIAL_JIEUT
	const INITIAL_SSANGJIEUT
	const INITIAL_CHIEUT
	const INITIAL_KIEUK
	const INITIAL_TIEUT
	const INITIAL_PIEUP
	const INITIAL_HIEUT

; medial vowels
	const_def 1
	const MEDIAL_A
	const MEDIAL_AE
	const MEDIAL_YA
	const MEDIAL_YAE
	const MEDIAL_EO
	const MEDIAL_E
	const MEDIAL_YEO
	const MEDIAL_YE
	const MEDIAL_O
	const MEDIAL_WA
	const MEDIAL_WAE
	const MEDIAL_OE
	const MEDIAL_YO
	const MEDIAL_U
	const MEDIAL_WO
	const MEDIAL_WE
	const MEDIAL_WI
	const MEDIAL_YU
	const MEDIAL_EU
	const MEDIAL_UI
	const MEDIAL_I

; final consonants
	const_def 1
	const FINAL_GIYEOK
	const FINAL_SSANGGIYEOK
	const FINAL_GIYEOK_SIOT
	const FINAL_NIEUN
	const FINAL_NIEUN_JIEUT
	const FINAL_NIEUN_HIEUT
	const FINAL_DIGEUT
	const FINAL_RIEUL
	const FINAL_RIEUL_GIYEOK
	const FINAL_RIEUL_MIEUM
	const FINAL_RIEUL_BIEUP
	const FINAL_RIEUL_SIOT
	const FINAL_RIEUL_TIEUT
	const FINAL_RIEUL_PIEUP
	const FINAL_RIEUL_HIEUT
	const FINAL_MIEUM
	const FINAL_BIEUP
	const FINAL_BIEUP_SIOT
	const FINAL_SIOT
	const FINAL_SSANGSIOT
	const FINAL_IEUNG
	const FINAL_JIEUT
	const FINAL_CHIEUT
	const FINAL_KIEUK
	const FINAL_TIEUT
	const FINAL_PIEUP
	const FINAL_HIEUT
DEF NUM_FINAL_CONSONANTS EQU const_value - 1

; illegal final consonants
DEF FINAL_SSANGDIGEUT EQU %11111
DEF FINAL_SSANGBIEUP  EQU %11111
DEF FINAL_SSANGJIEUT  EQU %11111

; syllable block masks
DEF INITIAL_BLOCK_MASK EQU %00000000_00011111
DEF MEDIAL_BLOCK_MASK  EQU %00000011_11100000
DEF FINAL_BLOCK_MASK   EQU %01111100_00000000
