	def_kr_table 6

	kr_charmap "셸", $00
	kr_charmap "솅", $01
	kr_charmap "소", $02
	kr_charmap "속", $03
	kr_charmap "솎", $04
	kr_charmap "손", $05
	kr_charmap "솔", $06
	kr_charmap "솖", $07
	kr_charmap "솜", $08
	kr_charmap "솝", $09
	kr_charmap "솟", $0a
	kr_charmap "송", $0b
	kr_charmap "솥", $0c
	kr_charmap "솨", $0d
	kr_charmap "솩", $0e
	kr_charmap "솬", $0f
	kr_charmap "솰", $10
	kr_charmap "솽", $11
	kr_charmap "쇄", $12
	kr_charmap "쇈", $13
	kr_charmap "쇌", $14
	kr_charmap "쇔", $15
	kr_charmap "쇗", $16
	kr_charmap "쇘", $17
	kr_charmap "쇠", $18
	kr_charmap "쇤", $19
	kr_charmap "쇨", $1a
	kr_charmap "쇰", $1b
	kr_charmap "쇱", $1c
	kr_charmap "쇳", $1d
	kr_charmap "쇼", $1e
	kr_charmap "쇽", $1f
	kr_charmap "숀", $20
	kr_charmap "숄", $21
	kr_charmap "숌", $22
	kr_charmap "숍", $23
	kr_charmap "숏", $24
	kr_charmap "숑", $25
	kr_charmap "수", $26
	kr_charmap "숙", $27
	kr_charmap "순", $28
	kr_charmap "숟", $29
	kr_charmap "술", $2a
	kr_charmap "숨", $2b
	kr_charmap "숩", $2c
	kr_charmap "숫", $2d
	kr_charmap "숭", $2e
	kr_charmap "쌰", $2f
	kr_charmap "쎼", $30
	kr_charmap "숯", $31
	kr_charmap "숱", $32
	kr_charmap "숲", $33
	kr_charmap "숴", $34
	kr_charmap "쉈", $35
	kr_charmap "쉐", $36
	kr_charmap "쉑", $37
	kr_charmap "쉔", $38
	kr_charmap "쉘", $39
	kr_charmap "쉠", $3a
	kr_charmap "쉥", $3b
	kr_charmap "쉬", $3c
	kr_charmap "쉭", $3d
	kr_charmap "쉰", $3e
	kr_charmap "쉴", $3f
	kr_charmap "쉼", $40
	kr_charmap "쉽", $41
	kr_charmap "쉿", $42
	kr_charmap "슁", $43
	kr_charmap "슈", $44
	kr_charmap "슉", $45
	kr_charmap "슐", $46
	kr_charmap "슘", $47
	kr_charmap "슛", $48
	kr_charmap "슝", $49
	kr_charmap "스", $4a
	kr_charmap "슥", $4b
	kr_charmap "슨", $4c
	kr_charmap "슬", $4d
	kr_charmap "슭", $4e
	kr_charmap "슴", $4f

	kr_charmap "습", $60
	kr_charmap "슷", $61
	kr_charmap "승", $62
	kr_charmap "시", $63
	kr_charmap "식", $64
	kr_charmap "신", $65
	kr_charmap "싣", $66
	kr_charmap "실", $67
	kr_charmap "싫", $68
	kr_charmap "심", $69
	kr_charmap "십", $6a
	kr_charmap "싯", $6b
	kr_charmap "싱", $6c
	kr_charmap "싶", $6d
	kr_charmap "싸", $6e
	kr_charmap "싹", $6f
	kr_charmap "싻", $70
	kr_charmap "싼", $71
	kr_charmap "쌀", $72
	kr_charmap "쌈", $73
	kr_charmap "쌉", $74
	kr_charmap "쌌", $75
	kr_charmap "쌍", $76
	kr_charmap "쌓", $77
	kr_charmap "쌔", $78
	kr_charmap "쌕", $79
	kr_charmap "쌘", $7a
	kr_charmap "쌜", $7b
	kr_charmap "쌤", $7c
	kr_charmap "쌥", $7d
	kr_charmap "쌨", $7e
	kr_charmap "쌩", $7f
	kr_charmap "썅", $80
	kr_charmap "써", $81
	kr_charmap "썩", $82
	kr_charmap "썬", $83
	kr_charmap "썰", $84
	kr_charmap "썲", $85
	kr_charmap "썸", $86
	kr_charmap "썹", $87
	kr_charmap "썼", $88
	kr_charmap "썽", $89
	kr_charmap "쎄", $8a
	kr_charmap "쎈", $8b
	kr_charmap "쎌", $8c
	kr_charmap "쏀", $8d
	kr_charmap "쏘", $8e
	kr_charmap "쏙", $8f
	kr_charmap "쏜", $90
	kr_charmap "쏟", $91
	kr_charmap "쏠", $92
	kr_charmap "쏢", $93
	kr_charmap "쏨", $94
	kr_charmap "쏩", $95
	kr_charmap "쏭", $96
	kr_charmap "쏴", $97
	kr_charmap "쏵", $98
	kr_charmap "쏸", $99
	kr_charmap "쐈", $9a
	kr_charmap "쐐", $9b
	kr_charmap "쐤", $9c
	kr_charmap "쐬", $9d
	kr_charmap "쐰", $9e

	kr_charmap "쓔", $a0
	kr_charmap "쐴", $a1
	kr_charmap "쐼", $a2
	kr_charmap "쐽", $a3
	kr_charmap "쑈", $a4
	kr_charmap "쑤", $a5
	kr_charmap "쑥", $a6
	kr_charmap "쑨", $a7
	kr_charmap "쑬", $a8
	kr_charmap "쑴", $a9
	kr_charmap "쑵", $aa
	kr_charmap "쑹", $ab
	kr_charmap "쒀", $ac
	kr_charmap "쒔", $ad
	kr_charmap "쒜", $ae
	kr_charmap "쒸", $af
	kr_charmap "쒼", $b0
	kr_charmap "쓩", $b1
	kr_charmap "쓰", $b2
	kr_charmap "쓱", $b3
	kr_charmap "쓴", $b4
	kr_charmap "쓸", $b5
	kr_charmap "쓺", $b6
	kr_charmap "쓿", $b7
	kr_charmap "씀", $b8
	kr_charmap "씁", $b9
	kr_charmap "씌", $ba
	kr_charmap "씐", $bb
	kr_charmap "씔", $bc
	kr_charmap "씜", $bd
	kr_charmap "씨", $be
	kr_charmap "씩", $bf
	kr_charmap "씬", $c0
	kr_charmap "씰", $c1
	kr_charmap "씸", $c2
	kr_charmap "씹", $c3
	kr_charmap "씻", $c4
	kr_charmap "씽", $c5
	kr_charmap "아", $c6
	kr_charmap "악", $c7
	kr_charmap "안", $c8
	kr_charmap "앉", $c9
	kr_charmap "않", $ca
	kr_charmap "알", $cb
	kr_charmap "앍", $cc
	kr_charmap "앎", $cd
	kr_charmap "앓", $ce
	kr_charmap "암", $cf
	kr_charmap "압", $d0
	kr_charmap "앗", $d1
	kr_charmap "았", $d2
	kr_charmap "앙", $d3
	kr_charmap "앝", $d4
	kr_charmap "앞", $d5
	kr_charmap "애", $d6
	kr_charmap "액", $d7
	kr_charmap "앤", $d8
	kr_charmap "앨", $d9
	kr_charmap "앰", $da
	kr_charmap "앱", $db
	kr_charmap "앳", $dc
	kr_charmap "앴", $dd
	kr_charmap "앵", $de
	kr_charmap "야", $df
	kr_charmap "약", $e0
	kr_charmap "얀", $e1
	kr_charmap "얄", $e2
	kr_charmap "얇", $e3
	kr_charmap "얌", $e4
	kr_charmap "얍", $e5
	kr_charmap "얏", $e6
	kr_charmap "양", $e7
	kr_charmap "얕", $e8
	kr_charmap "얗", $e9
	kr_charmap "얘", $ea
	kr_charmap "얜", $eb
	kr_charmap "얠", $ec
	kr_charmap "얩", $ed
	kr_charmap "어", $ee
	kr_charmap "억", $ef
	kr_charmap "언", $f0
	kr_charmap "얹", $f1
	kr_charmap "얻", $f2
	kr_charmap "얼", $f3
	kr_charmap "얽", $f4
	kr_charmap "얾", $f5
	kr_charmap "엄", $f6
	kr_charmap "업", $f7
	kr_charmap "없", $f8
	kr_charmap "엇", $f9
	kr_charmap "었", $fa
	kr_charmap "엉", $fb
	kr_charmap "엊", $fc
	kr_charmap "엌", $fd
	kr_charmap "엎", $fe
