	def_kr_table 7

	kr_charmap "에", $01
	kr_charmap "엑", $02
	kr_charmap "엔", $03
	kr_charmap "엘", $04
	kr_charmap "엠", $05
	kr_charmap "엡", $06
	kr_charmap "엣", $07
	kr_charmap "엥", $08
	kr_charmap "여", $09
	kr_charmap "역", $0a
	kr_charmap "엮", $0b
	kr_charmap "연", $0c
	kr_charmap "열", $0d
	kr_charmap "엶", $0e
	kr_charmap "엷", $0f
	kr_charmap "염", $10
	kr_charmap "엽", $11
	kr_charmap "엾", $12
	kr_charmap "엿", $13
	kr_charmap "였", $14
	kr_charmap "영", $15
	kr_charmap "옅", $16
	kr_charmap "옆", $17
	kr_charmap "옇", $18
	kr_charmap "예", $19
	kr_charmap "옌", $1a
	kr_charmap "옐", $1b
	kr_charmap "옘", $1c
	kr_charmap "옙", $1d
	kr_charmap "옛", $1e
	kr_charmap "옜", $1f
	kr_charmap "오", $20
	kr_charmap "옥", $21
	kr_charmap "온", $22
	kr_charmap "올", $23
	kr_charmap "옭", $24
	kr_charmap "옮", $25
	kr_charmap "옰", $26
	kr_charmap "옳", $27
	kr_charmap "옴", $28
	kr_charmap "옵", $29
	kr_charmap "옷", $2a
	kr_charmap "옹", $2b
	kr_charmap "옻", $2c
	kr_charmap "와", $2d
	kr_charmap "왁", $2e
	kr_charmap "완", $2f
	kr_charmap "왈", $30
	kr_charmap "왐", $31
	kr_charmap "왑", $32
	kr_charmap "왓", $33
	kr_charmap "왔", $34
	kr_charmap "왕", $35
	kr_charmap "왜", $36
	kr_charmap "왝", $37
	kr_charmap "왠", $38
	kr_charmap "왬", $39
	kr_charmap "왯", $3a
	kr_charmap "왱", $3b
	kr_charmap "외", $3c
	kr_charmap "왹", $3d
	kr_charmap "왼", $3e
	kr_charmap "욀", $3f
	kr_charmap "욈", $40
	kr_charmap "욉", $41
	kr_charmap "욋", $42
	kr_charmap "욍", $43
	kr_charmap "요", $44
	kr_charmap "욕", $45
	kr_charmap "욘", $46
	kr_charmap "욜", $47
	kr_charmap "욤", $48
	kr_charmap "욥", $49
	kr_charmap "욧", $4a
	kr_charmap "용", $4b
	kr_charmap "우", $4c
	kr_charmap "욱", $4d
	kr_charmap "운", $4e
	kr_charmap "울", $4f

	kr_charmap "욹", $60
	kr_charmap "욺", $61
	kr_charmap "움", $62
	kr_charmap "웁", $63
	kr_charmap "웃", $64
	kr_charmap "웅", $65
	kr_charmap "워", $66
	kr_charmap "웍", $67
	kr_charmap "원", $68
	kr_charmap "월", $69
	kr_charmap "웜", $6a
	kr_charmap "웝", $6b
	kr_charmap "웠", $6c
	kr_charmap "웡", $6d
	kr_charmap "웨", $6e

	kr_charmap "웩", $71
	kr_charmap "웬", $72
	kr_charmap "웰", $73
	kr_charmap "웸", $74
	kr_charmap "웹", $75
	kr_charmap "웽", $76
	kr_charmap "위", $77
	kr_charmap "윅", $78
	kr_charmap "윈", $79
	kr_charmap "윌", $7a
	kr_charmap "윔", $7b
	kr_charmap "윕", $7c
	kr_charmap "윗", $7d
	kr_charmap "윙", $7e
	kr_charmap "유", $7f
	kr_charmap "육", $80
	kr_charmap "윤", $81
	kr_charmap "율", $82
	kr_charmap "윰", $83
	kr_charmap "윱", $84
	kr_charmap "윳", $85
	kr_charmap "융", $86
	kr_charmap "윷", $87
	kr_charmap "으", $88
	kr_charmap "윽", $89
	kr_charmap "은", $8a
	kr_charmap "을", $8b
	kr_charmap "읆", $8c
	kr_charmap "음", $8d
	kr_charmap "읍", $8e
	kr_charmap "읏", $8f
	kr_charmap "응", $90
	kr_charmap "읒", $91
	kr_charmap "읓", $92
	kr_charmap "읔", $93
	kr_charmap "읕", $94
	kr_charmap "읖", $95
	kr_charmap "읗", $96
	kr_charmap "의", $97
	kr_charmap "읜", $98
	kr_charmap "읠", $99
	kr_charmap "읨", $9a
	kr_charmap "읫", $9b
	kr_charmap "이", $9c
	kr_charmap "익", $9d
	kr_charmap "인", $9e
	kr_charmap "일", $9f
	kr_charmap "읽", $a0
	kr_charmap "읾", $a1
	kr_charmap "잃", $a2
	kr_charmap "임", $a3
	kr_charmap "입", $a4
	kr_charmap "잇", $a5
	kr_charmap "있", $a6
	kr_charmap "잉", $a7
	kr_charmap "잊", $a8
	kr_charmap "잎", $a9
	kr_charmap "자", $aa
	kr_charmap "작", $ab
	kr_charmap "잔", $ac
	kr_charmap "잖", $ad
	kr_charmap "잗", $ae
	kr_charmap "잘", $af
	kr_charmap "잚", $b0
	kr_charmap "잠", $b1
	kr_charmap "잡", $b2
	kr_charmap "잣", $b3
	kr_charmap "잤", $b4
	kr_charmap "장", $b5
	kr_charmap "잦", $b6
	kr_charmap "재", $b7
	kr_charmap "잭", $b8
	kr_charmap "잰", $b9
	kr_charmap "잴", $ba
	kr_charmap "잼", $bb
	kr_charmap "잽", $bc
	kr_charmap "잿", $bd
	kr_charmap "쟀", $be
	kr_charmap "쟁", $bf
	kr_charmap "쟈", $c0
	kr_charmap "쟉", $c1
	kr_charmap "쟌", $c2
	kr_charmap "쟎", $c3
	kr_charmap "쟐", $c4
	kr_charmap "쟘", $c5
	kr_charmap "쟝", $c6
	kr_charmap "쟤", $c7
	kr_charmap "쟨", $c8
	kr_charmap "쟬", $c9
	kr_charmap "저", $ca
	kr_charmap "적", $cb
	kr_charmap "전", $cc
	kr_charmap "절", $cd
	kr_charmap "젊", $ce

	kr_charmap "점", $d1
	kr_charmap "접", $d2
	kr_charmap "젓", $d3
	kr_charmap "정", $d4
	kr_charmap "젖", $d5
	kr_charmap "제", $d6
	kr_charmap "젝", $d7
	kr_charmap "젠", $d8
	kr_charmap "젤", $d9
	kr_charmap "젬", $da
	kr_charmap "젭", $db
	kr_charmap "젯", $dc
	kr_charmap "젱", $dd
	kr_charmap "져", $de
	kr_charmap "젼", $df
	kr_charmap "졀", $e0
	kr_charmap "졈", $e1
	kr_charmap "졉", $e2
	kr_charmap "졌", $e3
	kr_charmap "졍", $e4
	kr_charmap "졔", $e5
	kr_charmap "조", $e6
	kr_charmap "족", $e7
	kr_charmap "존", $e8
	kr_charmap "졸", $e9
	kr_charmap "졺", $ea
	kr_charmap "좀", $eb
	kr_charmap "좁", $ec
	kr_charmap "좃", $ed
	kr_charmap "종", $ee
	kr_charmap "좆", $ef
	kr_charmap "좇", $f0
	kr_charmap "좋", $f1
	kr_charmap "좌", $f2
	kr_charmap "좍", $f3
	kr_charmap "좔", $f4
	kr_charmap "좝", $f5
	kr_charmap "좟", $f6
	kr_charmap "좡", $f7
	kr_charmap "좨", $f8
	kr_charmap "좼", $f9
	kr_charmap "좽", $fa
	kr_charmap "죄", $fb
	kr_charmap "죈", $fc
	kr_charmap "죌", $fd
	kr_charmap "죔", $fe
	kr_charmap "죕", $ff
