	def_kr_table 9

	kr_charmap "치", $01
	kr_charmap "칙", $02
	kr_charmap "친", $03
	kr_charmap "칟", $04
	kr_charmap "칠", $05
	kr_charmap "칡", $06
	kr_charmap "침", $07
	kr_charmap "칩", $08
	kr_charmap "칫", $09
	kr_charmap "칭", $0a
	kr_charmap "카", $0b
	kr_charmap "칵", $0c
	kr_charmap "칸", $0d
	kr_charmap "칼", $0e
	kr_charmap "캄", $0f
	kr_charmap "캅", $10
	kr_charmap "캇", $11
	kr_charmap "캉", $12
	kr_charmap "캐", $13
	kr_charmap "캑", $14
	kr_charmap "캔", $15
	kr_charmap "캘", $16
	kr_charmap "캠", $17
	kr_charmap "캡", $18
	kr_charmap "캣", $19
	kr_charmap "캤", $1a
	kr_charmap "캥", $1b
	kr_charmap "캬", $1c
	kr_charmap "캭", $1d
	kr_charmap "컁", $1e
	kr_charmap "커", $1f
	kr_charmap "컥", $20
	kr_charmap "컨", $21
	kr_charmap "컫", $22
	kr_charmap "컬", $23
	kr_charmap "컴", $24
	kr_charmap "컵", $25
	kr_charmap "컷", $26
	kr_charmap "컸", $27
	kr_charmap "컹", $28
	kr_charmap "케", $29
	kr_charmap "켁", $2a
	kr_charmap "켄", $2b
	kr_charmap "켈", $2c
	kr_charmap "켐", $2d
	kr_charmap "켑", $2e
	kr_charmap "켓", $2f
	kr_charmap "켕", $30
	kr_charmap "켜", $31
	kr_charmap "켠", $32
	kr_charmap "켤", $33
	kr_charmap "켬", $34
	kr_charmap "켭", $35
	kr_charmap "켯", $36
	kr_charmap "켰", $37
	kr_charmap "켱", $38
	kr_charmap "켸", $39
	kr_charmap "코", $3a
	kr_charmap "콕", $3b
	kr_charmap "콘", $3c
	kr_charmap "콜", $3d
	kr_charmap "콤", $3e
	kr_charmap "콥", $3f
	kr_charmap "콧", $40
	kr_charmap "콩", $41
	kr_charmap "콰", $42
	kr_charmap "콱", $43
	kr_charmap "콴", $44
	kr_charmap "콸", $45
	kr_charmap "쾀", $46
	kr_charmap "쾅", $47
	kr_charmap "쾌", $48
	kr_charmap "쾡", $49
	kr_charmap "쾨", $4a
	kr_charmap "쾰", $4b
	kr_charmap "쿄", $4c
	kr_charmap "쿠", $4d
	kr_charmap "쿡", $4e
	kr_charmap "쿤", $4f

	kr_charmap "쿨", $60
	kr_charmap "쿰", $61
	kr_charmap "쿱", $62
	kr_charmap "쿳", $63
	kr_charmap "쿵", $64
	kr_charmap "쿼", $65
	kr_charmap "퀀", $66
	kr_charmap "퀄", $67
	kr_charmap "퀑", $68
	kr_charmap "퀘", $69
	kr_charmap "퀭", $6a
	kr_charmap "퀴", $6b
	kr_charmap "퀵", $6c
	kr_charmap "퀸", $6d
	kr_charmap "퀼", $6e

	kr_charmap "큄", $71
	kr_charmap "큅", $72
	kr_charmap "큇", $73
	kr_charmap "큉", $74
	kr_charmap "큐", $75
	kr_charmap "큔", $76
	kr_charmap "큘", $77
	kr_charmap "큠", $78
	kr_charmap "크", $79
	kr_charmap "큭", $7a
	kr_charmap "큰", $7b
	kr_charmap "클", $7c
	kr_charmap "큼", $7d
	kr_charmap "큽", $7e
	kr_charmap "킁", $7f
	kr_charmap "키", $80
	kr_charmap "킥", $81
	kr_charmap "킨", $82
	kr_charmap "킬", $83
	kr_charmap "킴", $84
	kr_charmap "킵", $85
	kr_charmap "킷", $86
	kr_charmap "킹", $87
	kr_charmap "타", $88
	kr_charmap "탁", $89
	kr_charmap "탄", $8a
	kr_charmap "탈", $8b
	kr_charmap "탉", $8c
	kr_charmap "탐", $8d
	kr_charmap "탑", $8e
	kr_charmap "탓", $8f
	kr_charmap "탔", $90
	kr_charmap "탕", $91
	kr_charmap "태", $92
	kr_charmap "택", $93
	kr_charmap "탠", $94
	kr_charmap "탤", $95
	kr_charmap "탬", $96
	kr_charmap "탭", $97
	kr_charmap "탯", $98
	kr_charmap "탰", $99
	kr_charmap "탱", $9a
	kr_charmap "탸", $9b
	kr_charmap "턍", $9c
	kr_charmap "터", $9d
	kr_charmap "턱", $9e
	kr_charmap "턴", $9f
	kr_charmap "털", $a0
	kr_charmap "턺", $a1
	kr_charmap "텀", $a2
	kr_charmap "텁", $a3
	kr_charmap "텃", $a4
	kr_charmap "텄", $a5
	kr_charmap "텅", $a6
	kr_charmap "테", $a7
	kr_charmap "텍", $a8
	kr_charmap "텐", $a9
	kr_charmap "텔", $aa
	kr_charmap "템", $ab
	kr_charmap "텝", $ac
	kr_charmap "텟", $ad
	kr_charmap "텡", $ae
	kr_charmap "텨", $af
	kr_charmap "텬", $b0
	kr_charmap "텼", $b1
	kr_charmap "톄", $b2
	kr_charmap "톈", $b3
	kr_charmap "토", $b4
	kr_charmap "톡", $b5
	kr_charmap "톤", $b6
	kr_charmap "톨", $b7
	kr_charmap "톰", $b8
	kr_charmap "톱", $b9
	kr_charmap "톳", $ba
	kr_charmap "통", $bb
	kr_charmap "톺", $bc
	kr_charmap "톼", $bd
	kr_charmap "퇀", $be
	kr_charmap "퇘", $bf
	kr_charmap "퇴", $c0
	kr_charmap "퇸", $c1
	kr_charmap "툇", $c2
	kr_charmap "툉", $c3
	kr_charmap "툐", $c4
	kr_charmap "투", $c5
	kr_charmap "툭", $c6
	kr_charmap "툰", $c7
	kr_charmap "툴", $c8
	kr_charmap "툼", $c9
	kr_charmap "툽", $ca
	kr_charmap "툿", $cb
	kr_charmap "퉁", $cc
	kr_charmap "퉈", $cd
	kr_charmap "퉜", $ce

	kr_charmap "퉤", $d1
	kr_charmap "튀", $d2
	kr_charmap "튁", $d3
	kr_charmap "튄", $d4
	kr_charmap "튈", $d5
	kr_charmap "튐", $d6
	kr_charmap "튑", $d7
	kr_charmap "튕", $d8
	kr_charmap "튜", $d9
	kr_charmap "튠", $da
	kr_charmap "튤", $db
	kr_charmap "튬", $dc
	kr_charmap "튱", $dd
	kr_charmap "트", $de
	kr_charmap "특", $df
	kr_charmap "튼", $e0
	kr_charmap "튿", $e1
	kr_charmap "틀", $e2
	kr_charmap "틂", $e3
	kr_charmap "틈", $e4
	kr_charmap "틉", $e5
	kr_charmap "틋", $e6
	kr_charmap "틔", $e7
	kr_charmap "틘", $e8
	kr_charmap "틜", $e9
	kr_charmap "틤", $ea
	kr_charmap "틥", $eb
	kr_charmap "티", $ec
	kr_charmap "틱", $ed
	kr_charmap "틴", $ee
	kr_charmap "틸", $ef
	kr_charmap "팀", $f0
	kr_charmap "팁", $f1
	kr_charmap "팃", $f2
	kr_charmap "팅", $f3
	kr_charmap "파", $f4
	kr_charmap "팍", $f5
	kr_charmap "팎", $f6
	kr_charmap "판", $f7
	kr_charmap "팔", $f8
	kr_charmap "팖", $f9
	kr_charmap "팜", $fa
	kr_charmap "팝", $fb
	kr_charmap "팟", $fc
	kr_charmap "팠", $fd
	kr_charmap "팡", $fe
	kr_charmap "팥", $ff
