	def_kr_table 4

	kr_charmap "론", $00
	kr_charmap "롤", $01
	kr_charmap "롬", $02
	kr_charmap "롭", $03
	kr_charmap "롯", $04
	kr_charmap "롱", $05
	kr_charmap "롸", $06
	kr_charmap "롼", $07
	kr_charmap "뢍", $08
	kr_charmap "뢨", $09
	kr_charmap "뢰", $0a
	kr_charmap "뢴", $0b
	kr_charmap "뢸", $0c
	kr_charmap "룀", $0d
	kr_charmap "룁", $0e
	kr_charmap "룃", $0f
	kr_charmap "룅", $10
	kr_charmap "료", $11
	kr_charmap "룐", $12
	kr_charmap "룔", $13
	kr_charmap "룝", $14
	kr_charmap "룟", $15
	kr_charmap "룡", $16
	kr_charmap "루", $17
	kr_charmap "룩", $18
	kr_charmap "룬", $19
	kr_charmap "룰", $1a
	kr_charmap "룸", $1b
	kr_charmap "룹", $1c
	kr_charmap "룻", $1d
	kr_charmap "룽", $1e
	kr_charmap "뤄", $1f
	kr_charmap "뤘", $20
	kr_charmap "뤠", $21
	kr_charmap "뤼", $22
	kr_charmap "뤽", $23
	kr_charmap "륀", $24
	kr_charmap "륄", $25
	kr_charmap "륌", $26
	kr_charmap "륏", $27
	kr_charmap "륑", $28
	kr_charmap "류", $29
	kr_charmap "륙", $2a
	kr_charmap "륜", $2b
	kr_charmap "률", $2c
	kr_charmap "륨", $2d
	kr_charmap "륩", $2e

	kr_charmap "륫", $31
	kr_charmap "륭", $32
	kr_charmap "르", $33
	kr_charmap "륵", $34
	kr_charmap "른", $35
	kr_charmap "를", $36
	kr_charmap "름", $37
	kr_charmap "릅", $38
	kr_charmap "릇", $39
	kr_charmap "릉", $3a
	kr_charmap "릊", $3b
	kr_charmap "릍", $3c
	kr_charmap "릎", $3d
	kr_charmap "리", $3e
	kr_charmap "릭", $3f
	kr_charmap "린", $40
	kr_charmap "릴", $41
	kr_charmap "림", $42
	kr_charmap "립", $43
	kr_charmap "릿", $44
	kr_charmap "링", $45
	kr_charmap "마", $46
	kr_charmap "막", $47
	kr_charmap "만", $48
	kr_charmap "많", $49
	kr_charmap "맏", $4a
	kr_charmap "말", $4b
	kr_charmap "맑", $4c
	kr_charmap "맒", $4d
	kr_charmap "맘", $4e
	kr_charmap "맙", $4f

	kr_charmap "맛", $60
	kr_charmap "망", $61
	kr_charmap "맞", $62
	kr_charmap "맡", $63
	kr_charmap "맣", $64
	kr_charmap "매", $65
	kr_charmap "맥", $66
	kr_charmap "맨", $67
	kr_charmap "맬", $68
	kr_charmap "맴", $69
	kr_charmap "맵", $6a
	kr_charmap "맷", $6b
	kr_charmap "맸", $6c
	kr_charmap "맹", $6d
	kr_charmap "맺", $6e
	kr_charmap "먀", $6f
	kr_charmap "먁", $70
	kr_charmap "먈", $71
	kr_charmap "먕", $72
	kr_charmap "머", $73
	kr_charmap "먹", $74
	kr_charmap "먼", $75
	kr_charmap "멀", $76
	kr_charmap "멂", $77
	kr_charmap "멈", $78
	kr_charmap "멉", $79
	kr_charmap "멋", $7a
	kr_charmap "멍", $7b
	kr_charmap "멎", $7c
	kr_charmap "멓", $7d
	kr_charmap "메", $7e
	kr_charmap "멕", $7f
	kr_charmap "멘", $80
	kr_charmap "멜", $81
	kr_charmap "멤", $82
	kr_charmap "멥", $83
	kr_charmap "멧", $84
	kr_charmap "멨", $85
	kr_charmap "멩", $86
	kr_charmap "며", $87
	kr_charmap "멱", $88
	kr_charmap "면", $89
	kr_charmap "멸", $8a
	kr_charmap "몃", $8b
	kr_charmap "몄", $8c
	kr_charmap "명", $8d
	kr_charmap "몇", $8e
	kr_charmap "몌", $8f
	kr_charmap "모", $90
	kr_charmap "목", $91
	kr_charmap "몫", $92
	kr_charmap "몬", $93
	kr_charmap "몰", $94
	kr_charmap "몲", $95
	kr_charmap "몸", $96
	kr_charmap "몹", $97
	kr_charmap "못", $98
	kr_charmap "몽", $99
	kr_charmap "뫄", $9a
	kr_charmap "뫈", $9b
	kr_charmap "뫘", $9c
	kr_charmap "뫙", $9d
	kr_charmap "뫼", $9e

	kr_charmap "묀", $a1
	kr_charmap "묄", $a2
	kr_charmap "묍", $a3
	kr_charmap "묏", $a4
	kr_charmap "묑", $a5
	kr_charmap "묘", $a6
	kr_charmap "묜", $a7
	kr_charmap "묠", $a8
	kr_charmap "묩", $a9
	kr_charmap "묫", $aa
	kr_charmap "무", $ab
	kr_charmap "묵", $ac
	kr_charmap "묶", $ad
	kr_charmap "문", $ae
	kr_charmap "묻", $af
	kr_charmap "물", $b0
	kr_charmap "묽", $b1
	kr_charmap "묾", $b2
	kr_charmap "뭄", $b3
	kr_charmap "뭅", $b4
	kr_charmap "뭇", $b5
	kr_charmap "뭉", $b6
	kr_charmap "뭍", $b7
	kr_charmap "뭏", $b8
	kr_charmap "뭐", $b9
	kr_charmap "뭔", $ba
	kr_charmap "뭘", $bb
	kr_charmap "뭡", $bc
	kr_charmap "뭣", $bd
	kr_charmap "뭬", $be
	kr_charmap "뮈", $bf
	kr_charmap "뮌", $c0
	kr_charmap "뮐", $c1
	kr_charmap "뮤", $c2
	kr_charmap "뮨", $c3
	kr_charmap "뮬", $c4
	kr_charmap "뮴", $c5
	kr_charmap "뮷", $c6
	kr_charmap "므", $c7
	kr_charmap "믄", $c8
	kr_charmap "믈", $c9
	kr_charmap "믐", $ca
	kr_charmap "믓", $cb
	kr_charmap "미", $cc
	kr_charmap "믹", $cd
	kr_charmap "민", $ce
	kr_charmap "믿", $cf
	kr_charmap "밀", $d0
	kr_charmap "밂", $d1
	kr_charmap "밈", $d2
	kr_charmap "밉", $d3
	kr_charmap "밋", $d4
	kr_charmap "밌", $d5
	kr_charmap "밍", $d6
	kr_charmap "및", $d7
	kr_charmap "밑", $d8
	kr_charmap "바", $d9
	kr_charmap "박", $da
	kr_charmap "밖", $db
	kr_charmap "밗", $dc
	kr_charmap "반", $dd
	kr_charmap "받", $de
	kr_charmap "발", $df
	kr_charmap "밝", $e0
	kr_charmap "밞", $e1
	kr_charmap "밟", $e2
	kr_charmap "밤", $e3
	kr_charmap "밥", $e4
	kr_charmap "밧", $e5
	kr_charmap "방", $e6
	kr_charmap "밭", $e7
	kr_charmap "배", $e8
	kr_charmap "백", $e9
	kr_charmap "밴", $ea
	kr_charmap "밸", $eb
	kr_charmap "뱀", $ec
	kr_charmap "뱁", $ed
	kr_charmap "뱃", $ee
	kr_charmap "뱄", $ef
	kr_charmap "뱅", $f0
	kr_charmap "뱉", $f1
	kr_charmap "뱌", $f2
	kr_charmap "뱍", $f3
	kr_charmap "뱐", $f4
	kr_charmap "뱝", $f5
	kr_charmap "버", $f6
	kr_charmap "벅", $f7
	kr_charmap "번", $f8
	kr_charmap "벋", $f9
	kr_charmap "벌", $fa
	kr_charmap "벎", $fb
	kr_charmap "범", $fc
	kr_charmap "법", $fd
	kr_charmap "벗", $fe
