	def_kr_table 8

	kr_charmap "죗", $00
	kr_charmap "죙", $01
	kr_charmap "죠", $02
	kr_charmap "죡", $03
	kr_charmap "죤", $04
	kr_charmap "죵", $05
	kr_charmap "주", $06
	kr_charmap "죽", $07
	kr_charmap "준", $08
	kr_charmap "줄", $09
	kr_charmap "줅", $0a
	kr_charmap "줆", $0b
	kr_charmap "줌", $0c
	kr_charmap "줍", $0d
	kr_charmap "줏", $0e
	kr_charmap "중", $0f
	kr_charmap "줘", $10
	kr_charmap "줬", $11
	kr_charmap "줴", $12
	kr_charmap "쥐", $13
	kr_charmap "쥑", $14
	kr_charmap "쥔", $15
	kr_charmap "쥘", $16
	kr_charmap "쥠", $17
	kr_charmap "쥡", $18
	kr_charmap "쥣", $19
	kr_charmap "쥬", $1a
	kr_charmap "쥰", $1b
	kr_charmap "쥴", $1c
	kr_charmap "쥼", $1d
	kr_charmap "즈", $1e
	kr_charmap "즉", $1f
	kr_charmap "즌", $20
	kr_charmap "즐", $21
	kr_charmap "즘", $22
	kr_charmap "즙", $23
	kr_charmap "즛", $24
	kr_charmap "증", $25
	kr_charmap "지", $26
	kr_charmap "직", $27
	kr_charmap "진", $28
	kr_charmap "짇", $29
	kr_charmap "질", $2a
	kr_charmap "짊", $2b
	kr_charmap "짐", $2c
	kr_charmap "집", $2d
	kr_charmap "짓", $2e

	kr_charmap "쬬", $30
	kr_charmap "징", $31
	kr_charmap "짖", $32
	kr_charmap "짙", $33
	kr_charmap "짚", $34
	kr_charmap "짜", $35
	kr_charmap "짝", $36
	kr_charmap "짠", $37
	kr_charmap "짢", $38
	kr_charmap "짤", $39
	kr_charmap "짧", $3a
	kr_charmap "짬", $3b
	kr_charmap "짭", $3c
	kr_charmap "짯", $3d
	kr_charmap "짰", $3e
	kr_charmap "짱", $3f
	kr_charmap "째", $40
	kr_charmap "짹", $41
	kr_charmap "짼", $42
	kr_charmap "쨀", $43
	kr_charmap "쨈", $44
	kr_charmap "쨉", $45
	kr_charmap "쨋", $46
	kr_charmap "쨌", $47
	kr_charmap "쨍", $48
	kr_charmap "쨔", $49
	kr_charmap "쨘", $4a
	kr_charmap "쨩", $4b
	kr_charmap "쩌", $4c
	kr_charmap "쩍", $4d
	kr_charmap "쩐", $4e
	kr_charmap "쩔", $4f

	kr_charmap "쩜", $60
	kr_charmap "쩝", $61
	kr_charmap "쩟", $62
	kr_charmap "쩠", $63
	kr_charmap "쩡", $64
	kr_charmap "쩨", $65
	kr_charmap "쩽", $66
	kr_charmap "쪄", $67
	kr_charmap "쪘", $68
	kr_charmap "쪼", $69
	kr_charmap "쪽", $6a
	kr_charmap "쫀", $6b
	kr_charmap "쫄", $6c
	kr_charmap "쫌", $6d
	kr_charmap "쫍", $6e
	kr_charmap "쫏", $6f
	kr_charmap "쫑", $70
	kr_charmap "쫓", $71
	kr_charmap "쫘", $72
	kr_charmap "쫙", $73
	kr_charmap "쫠", $74
	kr_charmap "쫬", $75
	kr_charmap "쫴", $76
	kr_charmap "쬈", $77
	kr_charmap "쬐", $78
	kr_charmap "쬔", $79
	kr_charmap "쬘", $7a
	kr_charmap "쬠", $7b
	kr_charmap "쬡", $7c
	kr_charmap "쭁", $7d
	kr_charmap "쭈", $7e
	kr_charmap "쭉", $7f
	kr_charmap "쭌", $80
	kr_charmap "쭐", $81
	kr_charmap "쭘", $82
	kr_charmap "쭙", $83
	kr_charmap "쭝", $84
	kr_charmap "쭤", $85
	kr_charmap "쭸", $86
	kr_charmap "쭹", $87
	kr_charmap "쮜", $88
	kr_charmap "쮸", $89
	kr_charmap "쯔", $8a
	kr_charmap "쯤", $8b
	kr_charmap "쯧", $8c
	kr_charmap "쯩", $8d
	kr_charmap "찌", $8e
	kr_charmap "찍", $8f
	kr_charmap "찐", $90
	kr_charmap "찔", $91
	kr_charmap "찜", $92
	kr_charmap "찝", $93
	kr_charmap "찡", $94
	kr_charmap "찢", $95
	kr_charmap "찧", $96
	kr_charmap "차", $97
	kr_charmap "착", $98
	kr_charmap "찬", $99
	kr_charmap "찮", $9a
	kr_charmap "찰", $9b
	kr_charmap "참", $9c
	kr_charmap "찹", $9d
	kr_charmap "찻", $9e

	kr_charmap "찼", $a1
	kr_charmap "창", $a2
	kr_charmap "찾", $a3
	kr_charmap "채", $a4
	kr_charmap "책", $a5
	kr_charmap "챈", $a6
	kr_charmap "챌", $a7
	kr_charmap "챔", $a8
	kr_charmap "챕", $a9
	kr_charmap "챗", $aa
	kr_charmap "챘", $ab
	kr_charmap "챙", $ac
	kr_charmap "챠", $ad
	kr_charmap "챤", $ae
	kr_charmap "챦", $af
	kr_charmap "챨", $b0
	kr_charmap "챰", $b1
	kr_charmap "챵", $b2
	kr_charmap "처", $b3
	kr_charmap "척", $b4
	kr_charmap "천", $b5
	kr_charmap "철", $b6
	kr_charmap "첨", $b7
	kr_charmap "첩", $b8
	kr_charmap "첫", $b9
	kr_charmap "첬", $ba
	kr_charmap "청", $bb
	kr_charmap "체", $bc
	kr_charmap "첵", $bd
	kr_charmap "첸", $be
	kr_charmap "첼", $bf
	kr_charmap "쳄", $c0
	kr_charmap "쳅", $c1
	kr_charmap "쳇", $c2
	kr_charmap "쳉", $c3
	kr_charmap "쳐", $c4
	kr_charmap "쳔", $c5
	kr_charmap "쳤", $c6
	kr_charmap "쳬", $c7
	kr_charmap "쳰", $c8
	kr_charmap "촁", $c9
	kr_charmap "초", $ca
	kr_charmap "촉", $cb
	kr_charmap "촌", $cc
	kr_charmap "촐", $cd
	kr_charmap "촘", $ce
	kr_charmap "촙", $cf
	kr_charmap "촛", $d0
	kr_charmap "총", $d1
	kr_charmap "촤", $d2
	kr_charmap "촨", $d3
	kr_charmap "촬", $d4
	kr_charmap "촹", $d5
	kr_charmap "최", $d6
	kr_charmap "쵠", $d7
	kr_charmap "쵤", $d8
	kr_charmap "쵬", $d9
	kr_charmap "쵭", $da
	kr_charmap "쵯", $db
	kr_charmap "쵱", $dc
	kr_charmap "쵸", $dd
	kr_charmap "춈", $de
	kr_charmap "추", $df
	kr_charmap "축", $e0
	kr_charmap "춘", $e1
	kr_charmap "출", $e2
	kr_charmap "춤", $e3
	kr_charmap "춥", $e4
	kr_charmap "춧", $e5
	kr_charmap "충", $e6
	kr_charmap "춰", $e7
	kr_charmap "췄", $e8
	kr_charmap "췌", $e9
	kr_charmap "췐", $ea
	kr_charmap "취", $eb
	kr_charmap "췬", $ec
	kr_charmap "췰", $ed
	kr_charmap "췸", $ee
	kr_charmap "췹", $ef
	kr_charmap "췻", $f0
	kr_charmap "췽", $f1
	kr_charmap "츄", $f2
	kr_charmap "츈", $f3
	kr_charmap "츌", $f4
	kr_charmap "츔", $f5
	kr_charmap "츙", $f6
	kr_charmap "츠", $f7
	kr_charmap "측", $f8
	kr_charmap "츤", $f9
	kr_charmap "츨", $fa
	kr_charmap "츰", $fb
	kr_charmap "츱", $fc
	kr_charmap "츳", $fd
	kr_charmap "층", $fe
