	def_kr_table 2

	kr_charmap "꽥", $00
	kr_charmap "꽹", $01
	kr_charmap "꾀", $02
	kr_charmap "꾄", $03
	kr_charmap "꾈", $04
	kr_charmap "꾐", $05
	kr_charmap "꾑", $06
	kr_charmap "꾕", $07
	kr_charmap "꾜", $08
	kr_charmap "꾸", $09
	kr_charmap "꾹", $0a
	kr_charmap "꾼", $0b
	kr_charmap "꿀", $0c
	kr_charmap "꿇", $0d
	kr_charmap "꿈", $0e
	kr_charmap "꿉", $0f
	kr_charmap "꿋", $10
	kr_charmap "꿍", $11
	kr_charmap "꿎", $12
	kr_charmap "꿔", $13
	kr_charmap "꿜", $14
	kr_charmap "꿨", $15
	kr_charmap "꿩", $16
	kr_charmap "꿰", $17
	kr_charmap "꿱", $18
	kr_charmap "꿴", $19
	kr_charmap "꿸", $1a
	kr_charmap "뀀", $1b
	kr_charmap "뀁", $1c
	kr_charmap "뀄", $1d
	kr_charmap "뀌", $1e
	kr_charmap "뀐", $1f
	kr_charmap "뀔", $20
	kr_charmap "뀜", $21
	kr_charmap "뀝", $22
	kr_charmap "뀨", $23
	kr_charmap "끄", $24
	kr_charmap "끅", $25
	kr_charmap "끈", $26
	kr_charmap "끊", $27
	kr_charmap "끌", $28
	kr_charmap "끎", $29
	kr_charmap "끓", $2a
	kr_charmap "끔", $2b
	kr_charmap "끕", $2c
	kr_charmap "끗", $2d
	kr_charmap "끙", $2e

	kr_charmap "끝", $31
	kr_charmap "끼", $32
	kr_charmap "끽", $33
	kr_charmap "낀", $34
	kr_charmap "낄", $35
	kr_charmap "낌", $36
	kr_charmap "낍", $37
	kr_charmap "낏", $38
	kr_charmap "낑", $39
	kr_charmap "나", $3a
	kr_charmap "낙", $3b
	kr_charmap "낚", $3c
	kr_charmap "난", $3d
	kr_charmap "낟", $3e
	kr_charmap "날", $3f
	kr_charmap "낡", $40
	kr_charmap "낢", $41
	kr_charmap "남", $42
	kr_charmap "납", $43
	kr_charmap "낫", $44
	kr_charmap "났", $45
	kr_charmap "낭", $46
	kr_charmap "낮", $47
	kr_charmap "낯", $48
	kr_charmap "낱", $49
	kr_charmap "낳", $4a
	kr_charmap "내", $4b
	kr_charmap "낵", $4c
	kr_charmap "낸", $4d
	kr_charmap "낼", $4e
	kr_charmap "냄", $4f

	kr_charmap "냅", $60
	kr_charmap "냇", $61
	kr_charmap "냈", $62
	kr_charmap "냉", $63
	kr_charmap "냐", $64
	kr_charmap "냑", $65
	kr_charmap "냔", $66
	kr_charmap "냘", $67
	kr_charmap "냠", $68
	kr_charmap "냥", $69
	kr_charmap "너", $6a
	kr_charmap "넉", $6b
	kr_charmap "넋", $6c
	kr_charmap "넌", $6d
	kr_charmap "널", $6e
	kr_charmap "넒", $6f
	kr_charmap "넓", $70
	kr_charmap "넘", $71
	kr_charmap "넙", $72
	kr_charmap "넛", $73
	kr_charmap "넜", $74
	kr_charmap "넝", $75
	kr_charmap "넣", $76
	kr_charmap "네", $77
	kr_charmap "넥", $78
	kr_charmap "넨", $79
	kr_charmap "넬", $7a
	kr_charmap "넴", $7b
	kr_charmap "넵", $7c
	kr_charmap "넷", $7d
	kr_charmap "넸", $7e
	kr_charmap "넹", $7f
	kr_charmap "녀", $80
	kr_charmap "녁", $81
	kr_charmap "년", $82
	kr_charmap "녈", $83
	kr_charmap "념", $84
	kr_charmap "녑", $85
	kr_charmap "녔", $86
	kr_charmap "녕", $87
	kr_charmap "녘", $88
	kr_charmap "녜", $89
	kr_charmap "녠", $8a
	kr_charmap "노", $8b
	kr_charmap "녹", $8c
	kr_charmap "논", $8d
	kr_charmap "놀", $8e
	kr_charmap "놂", $8f
	kr_charmap "놈", $90
	kr_charmap "놉", $91
	kr_charmap "놋", $92
	kr_charmap "농", $93
	kr_charmap "높", $94
	kr_charmap "놓", $95
	kr_charmap "놔", $96
	kr_charmap "놘", $97
	kr_charmap "놜", $98
	kr_charmap "놨", $99
	kr_charmap "뇌", $9a
	kr_charmap "뇐", $9b
	kr_charmap "뇔", $9c
	kr_charmap "뇜", $9d
	kr_charmap "뇝", $9e

	kr_charmap "뇟", $a1
	kr_charmap "뇨", $a2
	kr_charmap "뇩", $a3
	kr_charmap "뇬", $a4
	kr_charmap "뇰", $a5
	kr_charmap "뇹", $a6
	kr_charmap "뇻", $a7
	kr_charmap "뇽", $a8
	kr_charmap "누", $a9
	kr_charmap "눅", $aa
	kr_charmap "눈", $ab
	kr_charmap "눋", $ac
	kr_charmap "눌", $ad
	kr_charmap "눔", $ae
	kr_charmap "눕", $af
	kr_charmap "눗", $b0
	kr_charmap "눙", $b1
	kr_charmap "눠", $b2
	kr_charmap "눴", $b3
	kr_charmap "눼", $b4
	kr_charmap "뉘", $b5
	kr_charmap "뉜", $b6
	kr_charmap "뉠", $b7
	kr_charmap "뉨", $b8
	kr_charmap "뉩", $b9
	kr_charmap "뉴", $ba
	kr_charmap "뉵", $bb
	kr_charmap "뉼", $bc
	kr_charmap "늄", $bd
	kr_charmap "늅", $be
	kr_charmap "늉", $bf
	kr_charmap "느", $c0
	kr_charmap "늑", $c1
	kr_charmap "는", $c2
	kr_charmap "늘", $c3
	kr_charmap "늙", $c4
	kr_charmap "늚", $c5
	kr_charmap "늠", $c6
	kr_charmap "늡", $c7
	kr_charmap "늣", $c8
	kr_charmap "능", $c9
	kr_charmap "늦", $ca
	kr_charmap "늪", $cb
	kr_charmap "늬", $cc
	kr_charmap "늰", $cd
	kr_charmap "늴", $ce
	kr_charmap "니", $cf
	kr_charmap "닉", $d0
	kr_charmap "닌", $d1
	kr_charmap "닐", $d2
	kr_charmap "닒", $d3
	kr_charmap "님", $d4
	kr_charmap "닙", $d5
	kr_charmap "닛", $d6
	kr_charmap "닝", $d7
	kr_charmap "닢", $d8
	kr_charmap "다", $d9
	kr_charmap "닥", $da
	kr_charmap "닦", $db
	kr_charmap "단", $dc
	kr_charmap "닫", $dd
	kr_charmap "달", $de
	kr_charmap "닭", $df
	kr_charmap "닮", $e0
	kr_charmap "닯", $e1
	kr_charmap "닳", $e2
	kr_charmap "담", $e3
	kr_charmap "답", $e4
	kr_charmap "닷", $e5
	kr_charmap "닸", $e6
	kr_charmap "당", $e7
	kr_charmap "닺", $e8
	kr_charmap "닻", $e9
	kr_charmap "닿", $ea
	kr_charmap "대", $eb
	kr_charmap "댁", $ec
	kr_charmap "댄", $ed
	kr_charmap "댈", $ee
	kr_charmap "댐", $ef
	kr_charmap "댑", $f0
	kr_charmap "댓", $f1
	kr_charmap "댔", $f2
	kr_charmap "댕", $f3

	kr_charmap "더", $f5
	kr_charmap "덕", $f6
	kr_charmap "덖", $f7
	kr_charmap "던", $f8
	kr_charmap "덛", $f9
	kr_charmap "덜", $fa
	kr_charmap "덞", $fb
	kr_charmap "덟", $fc
	kr_charmap "덤", $fd
	kr_charmap "덥", $fe
