	def_kr_table 10

	kr_charmap "패", $00
	kr_charmap "팩", $01
	kr_charmap "팬", $02
	kr_charmap "팰", $03
	kr_charmap "팸", $04
	kr_charmap "팹", $05
	kr_charmap "팻", $06
	kr_charmap "팼", $07
	kr_charmap "팽", $08
	kr_charmap "퍄", $09
	kr_charmap "퍅", $0a
	kr_charmap "퍼", $0b
	kr_charmap "퍽", $0c
	kr_charmap "펀", $0d
	kr_charmap "펄", $0e
	kr_charmap "펌", $0f
	kr_charmap "펍", $10
	kr_charmap "펏", $11
	kr_charmap "펐", $12
	kr_charmap "펑", $13
	kr_charmap "페", $14
	kr_charmap "펙", $15
	kr_charmap "펜", $16
	kr_charmap "펠", $17
	kr_charmap "펨", $18
	kr_charmap "펩", $19
	kr_charmap "펫", $1a
	kr_charmap "펭", $1b
	kr_charmap "펴", $1c
	kr_charmap "편", $1d
	kr_charmap "펼", $1e
	kr_charmap "폄", $1f
	kr_charmap "폅", $20
	kr_charmap "폈", $21
	kr_charmap "평", $22
	kr_charmap "폐", $23
	kr_charmap "폘", $24
	kr_charmap "폡", $25
	kr_charmap "폣", $26
	kr_charmap "포", $27
	kr_charmap "폭", $28
	kr_charmap "폰", $29
	kr_charmap "폴", $2a
	kr_charmap "폼", $2b
	kr_charmap "폽", $2c
	kr_charmap "폿", $2d
	kr_charmap "퐁", $2e

	kr_charmap "퐈", $31
	kr_charmap "퐝", $32
	kr_charmap "푀", $33
	kr_charmap "푄", $34
	kr_charmap "표", $35
	kr_charmap "푠", $36
	kr_charmap "푤", $37
	kr_charmap "푭", $38
	kr_charmap "푯", $39
	kr_charmap "푸", $3a
	kr_charmap "푹", $3b
	kr_charmap "푼", $3c
	kr_charmap "푿", $3d
	kr_charmap "풀", $3e
	kr_charmap "풂", $3f
	kr_charmap "품", $40
	kr_charmap "풉", $41
	kr_charmap "풋", $42
	kr_charmap "풍", $43
	kr_charmap "풔", $44
	kr_charmap "풩", $45
	kr_charmap "퓌", $46
	kr_charmap "퓐", $47
	kr_charmap "퓔", $48
	kr_charmap "퓜", $49
	kr_charmap "퓟", $4a
	kr_charmap "퓨", $4b
	kr_charmap "퓬", $4c
	kr_charmap "퓰", $4d
	kr_charmap "퓸", $4e
	kr_charmap "퓻", $4f

	kr_charmap "퓽", $60
	kr_charmap "프", $61
	kr_charmap "픈", $62
	kr_charmap "플", $63
	kr_charmap "픔", $64
	kr_charmap "픕", $65
	kr_charmap "픗", $66
	kr_charmap "피", $67
	kr_charmap "픽", $68
	kr_charmap "핀", $69
	kr_charmap "필", $6a
	kr_charmap "핌", $6b
	kr_charmap "핍", $6c
	kr_charmap "핏", $6d
	kr_charmap "핑", $6e
	kr_charmap "하", $6f
	kr_charmap "학", $70
	kr_charmap "한", $71
	kr_charmap "할", $72
	kr_charmap "핥", $73
	kr_charmap "함", $74
	kr_charmap "합", $75
	kr_charmap "핫", $76
	kr_charmap "항", $77
	kr_charmap "해", $78
	kr_charmap "핵", $79
	kr_charmap "핸", $7a
	kr_charmap "핼", $7b
	kr_charmap "햄", $7c
	kr_charmap "햅", $7d
	kr_charmap "햇", $7e
	kr_charmap "했", $7f
	kr_charmap "행", $80
	kr_charmap "햐", $81
	kr_charmap "향", $82
	kr_charmap "허", $83
	kr_charmap "헉", $84
	kr_charmap "헌", $85
	kr_charmap "헐", $86
	kr_charmap "헒", $87
	kr_charmap "험", $88
	kr_charmap "헙", $89
	kr_charmap "헛", $8a
	kr_charmap "헝", $8b
	kr_charmap "헤", $8c
	kr_charmap "헥", $8d
	kr_charmap "헨", $8e
	kr_charmap "헬", $8f
	kr_charmap "헴", $90
	kr_charmap "헵", $91
	kr_charmap "헷", $92
	kr_charmap "헹", $93
	kr_charmap "혀", $94
	kr_charmap "혁", $95
	kr_charmap "현", $96
	kr_charmap "혈", $97
	kr_charmap "혐", $98
	kr_charmap "협", $99
	kr_charmap "혓", $9a
	kr_charmap "혔", $9b
	kr_charmap "형", $9c
	kr_charmap "혜", $9d
	kr_charmap "혠", $9e

	kr_charmap "혤", $a1
	kr_charmap "혭", $a2
	kr_charmap "호", $a3
	kr_charmap "혹", $a4
	kr_charmap "혼", $a5
	kr_charmap "홀", $a6
	kr_charmap "홅", $a7
	kr_charmap "홈", $a8
	kr_charmap "홉", $a9
	kr_charmap "홋", $aa
	kr_charmap "홍", $ab
	kr_charmap "홑", $ac
	kr_charmap "화", $ad
	kr_charmap "확", $ae
	kr_charmap "환", $af
	kr_charmap "활", $b0
	kr_charmap "홧", $b1
	kr_charmap "황", $b2
	kr_charmap "홰", $b3
	kr_charmap "홱", $b4
	kr_charmap "홴", $b5
	kr_charmap "횃", $b6
	kr_charmap "횅", $b7
	kr_charmap "회", $b8
	kr_charmap "획", $b9
	kr_charmap "횐", $ba
	kr_charmap "횔", $bb
	kr_charmap "횝", $bc
	kr_charmap "횟", $bd
	kr_charmap "횡", $be
	kr_charmap "효", $bf
	kr_charmap "횬", $c0
	kr_charmap "횰", $c1
	kr_charmap "횹", $c2
	kr_charmap "횻", $c3
	kr_charmap "후", $c4
	kr_charmap "훅", $c5
	kr_charmap "훈", $c6
	kr_charmap "훌", $c7
	kr_charmap "훑", $c8
	kr_charmap "훔", $c9
	kr_charmap "훗", $ca
	kr_charmap "훙", $cb
	kr_charmap "훠", $cc
	kr_charmap "훤", $cd
	kr_charmap "훨", $ce
	kr_charmap "훰", $cf
	kr_charmap "훵", $d0
	kr_charmap "훼", $d1
	kr_charmap "훽", $d2
	kr_charmap "휀", $d3
	kr_charmap "휄", $d4
	kr_charmap "휑", $d5
	kr_charmap "휘", $d6
	kr_charmap "휙", $d7
	kr_charmap "휜", $d8
	kr_charmap "휠", $d9
	kr_charmap "휨", $da
	kr_charmap "휩", $db
	kr_charmap "휫", $dc
	kr_charmap "휭", $dd
	kr_charmap "휴", $de
	kr_charmap "휵", $df
	kr_charmap "휸", $e0
	kr_charmap "휼", $e1
	kr_charmap "흄", $e2
	kr_charmap "흇", $e3
	kr_charmap "흉", $e4
	kr_charmap "흐", $e5
	kr_charmap "흑", $e6
	kr_charmap "흔", $e7
	kr_charmap "흖", $e8
	kr_charmap "흗", $e9
	kr_charmap "흘", $ea
	kr_charmap "흙", $eb
	kr_charmap "흠", $ec
	kr_charmap "흡", $ed
	kr_charmap "흣", $ee
	kr_charmap "흥", $ef
	kr_charmap "흩", $f0
	kr_charmap "희", $f1
	kr_charmap "흰", $f2
	kr_charmap "흴", $f3
	kr_charmap "흼", $f4
	kr_charmap "흽", $f5
	kr_charmap "힁", $f6
	kr_charmap "히", $f7
	kr_charmap "힉", $f8
	kr_charmap "힌", $f9
	kr_charmap "힐", $fa
	kr_charmap "힘", $fb
	kr_charmap "힙", $fc
	kr_charmap "힛", $fd
	kr_charmap "힝", $fe
