	def_kr_table 3

	kr_charmap "덧", $01
	kr_charmap "덩", $02
	kr_charmap "덫", $03
	kr_charmap "덮", $04
	kr_charmap "데", $05
	kr_charmap "덱", $06
	kr_charmap "덴", $07
	kr_charmap "델", $08
	kr_charmap "뎀", $09
	kr_charmap "뎁", $0a
	kr_charmap "뎃", $0b
	kr_charmap "뎄", $0c
	kr_charmap "뎅", $0d
	kr_charmap "뎌", $0e
	kr_charmap "뎐", $0f
	kr_charmap "뎔", $10
	kr_charmap "뎠", $11
	kr_charmap "뎡", $12
	kr_charmap "뎨", $13
	kr_charmap "뎬", $14
	kr_charmap "도", $15
	kr_charmap "독", $16
	kr_charmap "돈", $17
	kr_charmap "돋", $18
	kr_charmap "돌", $19
	kr_charmap "돎", $1a

	kr_charmap "돔", $1c
	kr_charmap "돕", $1d
	kr_charmap "돗", $1e
	kr_charmap "동", $1f
	kr_charmap "돛", $20
	kr_charmap "돝", $21
	kr_charmap "돠", $22
	kr_charmap "돤", $23
	kr_charmap "돨", $24
	kr_charmap "돼", $25
	kr_charmap "됐", $26
	kr_charmap "되", $27
	kr_charmap "된", $28
	kr_charmap "될", $29
	kr_charmap "됨", $2a
	kr_charmap "됩", $2b
	kr_charmap "됫", $2c
	kr_charmap "됴", $2d
	kr_charmap "두", $2e
	kr_charmap "둑", $2f
	kr_charmap "둔", $30
	kr_charmap "둘", $31
	kr_charmap "둠", $32
	kr_charmap "둡", $33
	kr_charmap "둣", $34
	kr_charmap "둥", $35
	kr_charmap "둬", $36
	kr_charmap "뒀", $37
	kr_charmap "뒈", $38
	kr_charmap "뒝", $39
	kr_charmap "뒤", $3a
	kr_charmap "뒨", $3b
	kr_charmap "뒬", $3c
	kr_charmap "뒵", $3d
	kr_charmap "뒷", $3e
	kr_charmap "뒹", $3f
	kr_charmap "듀", $40
	kr_charmap "듄", $41
	kr_charmap "듈", $42
	kr_charmap "듐", $43
	kr_charmap "듕", $44
	kr_charmap "드", $45
	kr_charmap "득", $46
	kr_charmap "든", $47
	kr_charmap "듣", $48
	kr_charmap "들", $49
	kr_charmap "듦", $4a
	kr_charmap "듬", $4b
	kr_charmap "듭", $4c
	kr_charmap "듯", $4d
	kr_charmap "등", $4e
	kr_charmap "듸", $4f

	kr_charmap "디", $60
	kr_charmap "딕", $61
	kr_charmap "딘", $62
	kr_charmap "딛", $63
	kr_charmap "딜", $64
	kr_charmap "딤", $65
	kr_charmap "딥", $66
	kr_charmap "딧", $67
	kr_charmap "딨", $68
	kr_charmap "딩", $69
	kr_charmap "딪", $6a
	kr_charmap "따", $6b
	kr_charmap "딱", $6c
	kr_charmap "딴", $6d
	kr_charmap "딸", $6e

	kr_charmap "땀", $71
	kr_charmap "땁", $72
	kr_charmap "땃", $73
	kr_charmap "땄", $74
	kr_charmap "땅", $75
	kr_charmap "땋", $76
	kr_charmap "때", $77
	kr_charmap "땍", $78
	kr_charmap "땐", $79
	kr_charmap "땔", $7a
	kr_charmap "땜", $7b
	kr_charmap "땝", $7c
	kr_charmap "땟", $7d
	kr_charmap "땠", $7e
	kr_charmap "땡", $7f
	kr_charmap "떠", $80
	kr_charmap "떡", $81
	kr_charmap "떤", $82
	kr_charmap "떨", $83
	kr_charmap "떪", $84
	kr_charmap "떫", $85
	kr_charmap "떰", $86
	kr_charmap "떱", $87
	kr_charmap "떳", $88
	kr_charmap "떴", $89
	kr_charmap "떵", $8a
	kr_charmap "떻", $8b
	kr_charmap "떼", $8c
	kr_charmap "떽", $8d
	kr_charmap "뗀", $8e
	kr_charmap "뗄", $8f
	kr_charmap "뗌", $90
	kr_charmap "뗍", $91
	kr_charmap "뗏", $92
	kr_charmap "뗐", $93
	kr_charmap "뗑", $94
	kr_charmap "뗘", $95
	kr_charmap "뗬", $96
	kr_charmap "또", $97
	kr_charmap "똑", $98
	kr_charmap "똔", $99
	kr_charmap "똘", $9a
	kr_charmap "똥", $9b
	kr_charmap "똬", $9c
	kr_charmap "똴", $9d
	kr_charmap "뙈", $9e
	kr_charmap "뙤", $9f
	kr_charmap "뙨", $a0
	kr_charmap "뚜", $a1
	kr_charmap "뚝", $a2
	kr_charmap "뚠", $a3
	kr_charmap "뚤", $a4
	kr_charmap "뚫", $a5
	kr_charmap "뚬", $a6
	kr_charmap "뚱", $a7
	kr_charmap "뛔", $a8
	kr_charmap "뛰", $a9
	kr_charmap "뛴", $aa
	kr_charmap "뛸", $ab
	kr_charmap "뜀", $ac
	kr_charmap "뜁", $ad
	kr_charmap "뜅", $ae
	kr_charmap "뜨", $af
	kr_charmap "뜩", $b0
	kr_charmap "뜬", $b1
	kr_charmap "뜯", $b2
	kr_charmap "뜰", $b3
	kr_charmap "뜸", $b4
	kr_charmap "뜹", $b5
	kr_charmap "뜻", $b6
	kr_charmap "띄", $b7
	kr_charmap "띈", $b8
	kr_charmap "띌", $b9
	kr_charmap "띔", $ba
	kr_charmap "띕", $bb
	kr_charmap "띠", $bc
	kr_charmap "띤", $bd
	kr_charmap "띨", $be
	kr_charmap "띰", $bf
	kr_charmap "띱", $c0
	kr_charmap "띳", $c1
	kr_charmap "띵", $c2
	kr_charmap "라", $c3
	kr_charmap "락", $c4
	kr_charmap "란", $c5
	kr_charmap "랄", $c6
	kr_charmap "람", $c7
	kr_charmap "랍", $c8
	kr_charmap "랏", $c9
	kr_charmap "랐", $ca
	kr_charmap "랑", $cb
	kr_charmap "랒", $cc
	kr_charmap "랖", $cd
	kr_charmap "랗", $ce

	kr_charmap "뢔", $d0
	kr_charmap "래", $d1
	kr_charmap "랙", $d2
	kr_charmap "랜", $d3
	kr_charmap "랠", $d4
	kr_charmap "램", $d5
	kr_charmap "랩", $d6
	kr_charmap "랫", $d7
	kr_charmap "랬", $d8
	kr_charmap "랭", $d9
	kr_charmap "랴", $da
	kr_charmap "략", $db
	kr_charmap "랸", $dc
	kr_charmap "럇", $dd
	kr_charmap "량", $de
	kr_charmap "러", $df
	kr_charmap "럭", $e0
	kr_charmap "런", $e1
	kr_charmap "럴", $e2
	kr_charmap "럼", $e3
	kr_charmap "럽", $e4
	kr_charmap "럿", $e5
	kr_charmap "렀", $e6
	kr_charmap "렁", $e7
	kr_charmap "렇", $e8
	kr_charmap "레", $e9
	kr_charmap "렉", $ea
	kr_charmap "렌", $eb
	kr_charmap "렐", $ec
	kr_charmap "렘", $ed
	kr_charmap "렙", $ee
	kr_charmap "렛", $ef
	kr_charmap "렝", $f0
	kr_charmap "려", $f1
	kr_charmap "력", $f2
	kr_charmap "련", $f3
	kr_charmap "렬", $f4
	kr_charmap "렴", $f5
	kr_charmap "렵", $f6
	kr_charmap "렷", $f7
	kr_charmap "렸", $f8
	kr_charmap "령", $f9
	kr_charmap "례", $fa
	kr_charmap "롄", $fb
	kr_charmap "롑", $fc
	kr_charmap "롓", $fd
	kr_charmap "로", $fe
	kr_charmap "록", $ff
