	def_kr_table 1

	kr_charmap "가", $01
	kr_charmap "각", $02
	kr_charmap "간", $03
	kr_charmap "갇", $04
	kr_charmap "갈", $05
	kr_charmap "갉", $06
	kr_charmap "갊", $07
	kr_charmap "감", $08
	kr_charmap "갑", $09
	kr_charmap "값", $0a
	kr_charmap "갓", $0b
	kr_charmap "갔", $0c
	kr_charmap "강", $0d
	kr_charmap "갖", $0e
	kr_charmap "갗", $0f
	kr_charmap "같", $10
	kr_charmap "갚", $11
	kr_charmap "갛", $12
	kr_charmap "개", $13
	kr_charmap "객", $14
	kr_charmap "갠", $15
	kr_charmap "갤", $16
	kr_charmap "갬", $17
	kr_charmap "갭", $18
	kr_charmap "갯", $19
	kr_charmap "갰", $1a
	kr_charmap "갱", $1b
	kr_charmap "갸", $1c
	kr_charmap "갹", $1d
	kr_charmap "갼", $1e
	kr_charmap "걀", $1f
	kr_charmap "걋", $20
	kr_charmap "걍", $21
	kr_charmap "걔", $22
	kr_charmap "걘", $23
	kr_charmap "걜", $24
	kr_charmap "거", $25
	kr_charmap "걱", $26
	kr_charmap "건", $27
	kr_charmap "걷", $28
	kr_charmap "걸", $29
	kr_charmap "걺", $2a
	kr_charmap "검", $2b
	kr_charmap "겁", $2c
	kr_charmap "것", $2d
	kr_charmap "겄", $2e
	kr_charmap "겅", $2f
	kr_charmap "겆", $30
	kr_charmap "겉", $31
	kr_charmap "겊", $32
	kr_charmap "겋", $33
	kr_charmap "게", $34
	kr_charmap "겐", $35
	kr_charmap "겔", $36
	kr_charmap "겜", $37
	kr_charmap "겝", $38
	kr_charmap "겟", $39
	kr_charmap "겠", $3a
	kr_charmap "겡", $3b
	kr_charmap "겨", $3c
	kr_charmap "격", $3d
	kr_charmap "겪", $3e
	kr_charmap "견", $3f
	kr_charmap "겯", $40
	kr_charmap "결", $41
	kr_charmap "겹", $42
	kr_charmap "겸", $43
	kr_charmap "겻", $44
	kr_charmap "겼", $45
	kr_charmap "경", $46
	kr_charmap "곁", $47
	kr_charmap "계", $48
	kr_charmap "곈", $49
	kr_charmap "곌", $4a
	kr_charmap "곕", $4b
	kr_charmap "곗", $4c
	kr_charmap "고", $4d
	kr_charmap "곡", $4e
	kr_charmap "곤", $4f

	kr_charmap "곧", $60
	kr_charmap "골", $61
	kr_charmap "곪", $62
	kr_charmap "곬", $63
	kr_charmap "곯", $64
	kr_charmap "곰", $65
	kr_charmap "곱", $66
	kr_charmap "곳", $67
	kr_charmap "공", $68
	kr_charmap "곶", $69
	kr_charmap "과", $6a
	kr_charmap "곽", $6b
	kr_charmap "관", $6c
	kr_charmap "괄", $6d
	kr_charmap "괆", $6e

	kr_charmap "괌", $71
	kr_charmap "괍", $72
	kr_charmap "괏", $73
	kr_charmap "광", $74
	kr_charmap "괘", $75
	kr_charmap "괜", $76
	kr_charmap "괠", $77
	kr_charmap "괩", $78
	kr_charmap "괬", $79
	kr_charmap "괭", $7a
	kr_charmap "괴", $7b
	kr_charmap "괵", $7c
	kr_charmap "괸", $7d
	kr_charmap "괼", $7e
	kr_charmap "괻", $7f
	kr_charmap "굅", $80
	kr_charmap "굇", $81
	kr_charmap "굉", $82
	kr_charmap "교", $83
	kr_charmap "굔", $84
	kr_charmap "굘", $85
	kr_charmap "굡", $86
	kr_charmap "굣", $87
	kr_charmap "구", $88
	kr_charmap "국", $89
	kr_charmap "군", $8a
	kr_charmap "굳", $8b
	kr_charmap "굴", $8c
	kr_charmap "굵", $8d
	kr_charmap "굶", $8e
	kr_charmap "굻", $8f
	kr_charmap "굼", $90
	kr_charmap "굽", $91
	kr_charmap "굿", $92
	kr_charmap "궁", $93
	kr_charmap "궂", $94
	kr_charmap "궈", $95
	kr_charmap "궉", $96
	kr_charmap "권", $97
	kr_charmap "궐", $98
	kr_charmap "궜", $99
	kr_charmap "궝", $9a
	kr_charmap "궤", $9b
	kr_charmap "궷", $9c
	kr_charmap "귀", $9d
	kr_charmap "귁", $9e
	kr_charmap "귄", $9f
	kr_charmap "귈", $a0
	kr_charmap "귐", $a1
	kr_charmap "귑", $a2
	kr_charmap "귓", $a3
	kr_charmap "규", $a4
	kr_charmap "균", $a5
	kr_charmap "귤", $a6
	kr_charmap "그", $a7
	kr_charmap "극", $a8
	kr_charmap "근", $a9
	kr_charmap "귿", $aa
	kr_charmap "글", $ab
	kr_charmap "긁", $ac
	kr_charmap "금", $ad
	kr_charmap "급", $ae
	kr_charmap "긋", $af
	kr_charmap "긍", $b0
	kr_charmap "긔", $b1
	kr_charmap "기", $b2
	kr_charmap "긱", $b3
	kr_charmap "긴", $b4
	kr_charmap "긷", $b5
	kr_charmap "길", $b6
	kr_charmap "긺", $b7
	kr_charmap "김", $b8
	kr_charmap "깁", $b9
	kr_charmap "깃", $ba
	kr_charmap "깅", $bb
	kr_charmap "깆", $bc
	kr_charmap "깊", $bd
	kr_charmap "까", $be
	kr_charmap "깍", $bf
	kr_charmap "깎", $c0
	kr_charmap "깐", $c1
	kr_charmap "깔", $c2
	kr_charmap "깖", $c3
	kr_charmap "깜", $c4
	kr_charmap "깝", $c5
	kr_charmap "깟", $c6
	kr_charmap "깠", $c7
	kr_charmap "깡", $c8
	kr_charmap "깥", $c9
	kr_charmap "깨", $ca
	kr_charmap "깩", $cb
	kr_charmap "깬", $cc
	kr_charmap "깰", $cd
	kr_charmap "깸", $ce

	kr_charmap "깹", $d1
	kr_charmap "깻", $d2
	kr_charmap "깼", $d3
	kr_charmap "깽", $d4
	kr_charmap "꺄", $d5
	kr_charmap "꺅", $d6
	kr_charmap "꺌", $d7
	kr_charmap "꺼", $d8
	kr_charmap "꺽", $d9
	kr_charmap "꺾", $da
	kr_charmap "껀", $db
	kr_charmap "껄", $dc
	kr_charmap "껌", $dd
	kr_charmap "껍", $de
	kr_charmap "껏", $df
	kr_charmap "껐", $e0
	kr_charmap "껑", $e1
	kr_charmap "께", $e2
	kr_charmap "껙", $e3
	kr_charmap "껜", $e4
	kr_charmap "껨", $e5
	kr_charmap "껫", $e6
	kr_charmap "껭", $e7
	kr_charmap "껴", $e8
	kr_charmap "껸", $e9
	kr_charmap "껼", $ea
	kr_charmap "꼇", $eb
	kr_charmap "꼈", $ec
	kr_charmap "꼍", $ed
	kr_charmap "꼐", $ee
	kr_charmap "꼬", $ef
	kr_charmap "꼭", $f0
	kr_charmap "꼰", $f1
	kr_charmap "꼲", $f2
	kr_charmap "꼴", $f3
	kr_charmap "꼼", $f4
	kr_charmap "꼽", $f5
	kr_charmap "꼿", $f6
	kr_charmap "꽁", $f7
	kr_charmap "꽂", $f8
	kr_charmap "꽃", $f9
	kr_charmap "꽈", $fa
	kr_charmap "꽉", $fb
	kr_charmap "꽐", $fc
	kr_charmap "꽜", $fd
	kr_charmap "꽝", $fe
	kr_charmap "꽤", $ff
