	def_kr_table 5

	kr_charmap "벙", $01
	kr_charmap "벚", $02
	kr_charmap "베", $03
	kr_charmap "벡", $04
	kr_charmap "벤", $05
	kr_charmap "벧", $06
	kr_charmap "벨", $07
	kr_charmap "벰", $08
	kr_charmap "벱", $09
	kr_charmap "벳", $0a
	kr_charmap "벴", $0b
	kr_charmap "벵", $0c
	kr_charmap "벼", $0d
	kr_charmap "벽", $0e
	kr_charmap "변", $0f
	kr_charmap "별", $10
	kr_charmap "볍", $11
	kr_charmap "볏", $12
	kr_charmap "볐", $13
	kr_charmap "병", $14
	kr_charmap "볕", $15
	kr_charmap "볘", $16
	kr_charmap "볜", $17
	kr_charmap "보", $18
	kr_charmap "복", $19
	kr_charmap "볶", $1a
	kr_charmap "본", $1b
	kr_charmap "볼", $1c
	kr_charmap "봄", $1d
	kr_charmap "봅", $1e
	kr_charmap "봇", $1f
	kr_charmap "봉", $20
	kr_charmap "봐", $21
	kr_charmap "봔", $22
	kr_charmap "봤", $23
	kr_charmap "봬", $24
	kr_charmap "뵀", $25
	kr_charmap "뵈", $26
	kr_charmap "뵉", $27
	kr_charmap "뵌", $28
	kr_charmap "뵐", $29
	kr_charmap "뵘", $2a
	kr_charmap "뵙", $2b
	kr_charmap "뵤", $2c
	kr_charmap "뵨", $2d
	kr_charmap "부", $2e
	kr_charmap "북", $2f
	kr_charmap "분", $30
	kr_charmap "붇", $31
	kr_charmap "불", $32
	kr_charmap "붉", $33
	kr_charmap "붊", $34
	kr_charmap "붐", $35
	kr_charmap "붑", $36
	kr_charmap "붓", $37
	kr_charmap "붕", $38
	kr_charmap "붙", $39
	kr_charmap "붚", $3a
	kr_charmap "붜", $3b
	kr_charmap "붤", $3c
	kr_charmap "붰", $3d
	kr_charmap "붸", $3e
	kr_charmap "뷔", $3f
	kr_charmap "뷕", $40
	kr_charmap "뷘", $41
	kr_charmap "뷜", $42
	kr_charmap "뷩", $43
	kr_charmap "뷰", $44
	kr_charmap "뷴", $45
	kr_charmap "뷸", $46
	kr_charmap "븀", $47
	kr_charmap "븃", $48
	kr_charmap "븅", $49
	kr_charmap "브", $4a
	kr_charmap "븍", $4b
	kr_charmap "븐", $4c
	kr_charmap "블", $4d
	kr_charmap "븜", $4e
	kr_charmap "븝", $4f

	kr_charmap "븟", $60
	kr_charmap "비", $61
	kr_charmap "빅", $62
	kr_charmap "빈", $63
	kr_charmap "빌", $64
	kr_charmap "빎", $65
	kr_charmap "빔", $66
	kr_charmap "빕", $67
	kr_charmap "빗", $68
	kr_charmap "빙", $69
	kr_charmap "빚", $6a
	kr_charmap "빛", $6b
	kr_charmap "빠", $6c
	kr_charmap "빡", $6d
	kr_charmap "빤", $6e

	kr_charmap "빨", $71
	kr_charmap "빪", $72
	kr_charmap "빰", $73
	kr_charmap "빱", $74
	kr_charmap "빳", $75
	kr_charmap "빴", $76
	kr_charmap "빵", $77
	kr_charmap "빻", $78
	kr_charmap "빼", $79
	kr_charmap "빽", $7a
	kr_charmap "뺀", $7b
	kr_charmap "뺄", $7c
	kr_charmap "뺌", $7d
	kr_charmap "뺍", $7e
	kr_charmap "뺏", $7f
	kr_charmap "뺐", $80
	kr_charmap "뺑", $81
	kr_charmap "뺘", $82
	kr_charmap "뺙", $83
	kr_charmap "뺨", $84
	kr_charmap "뻐", $85
	kr_charmap "뻑", $86
	kr_charmap "뻔", $87
	kr_charmap "뻗", $88
	kr_charmap "뻘", $89
	kr_charmap "뻠", $8a
	kr_charmap "뻣", $8b
	kr_charmap "뻤", $8c
	kr_charmap "뻥", $8d
	kr_charmap "뻬", $8e
	kr_charmap "뼁", $8f
	kr_charmap "뼈", $90
	kr_charmap "뼉", $91
	kr_charmap "뼘", $92
	kr_charmap "뼙", $93
	kr_charmap "뼛", $94
	kr_charmap "뼜", $95
	kr_charmap "뼝", $96
	kr_charmap "뽀", $97
	kr_charmap "뽁", $98
	kr_charmap "뽄", $99
	kr_charmap "뽈", $9a
	kr_charmap "뽐", $9b
	kr_charmap "뽑", $9c
	kr_charmap "뽕", $9d
	kr_charmap "뾔", $9e
	kr_charmap "뾰", $9f
	kr_charmap "뿅", $a0
	kr_charmap "뿌", $a1
	kr_charmap "뿍", $a2
	kr_charmap "뿐", $a3
	kr_charmap "뿔", $a4
	kr_charmap "뿜", $a5
	kr_charmap "뿟", $a6
	kr_charmap "뿡", $a7
	kr_charmap "쀼", $a8
	kr_charmap "쁑", $a9
	kr_charmap "쁘", $aa
	kr_charmap "쁜", $ab
	kr_charmap "쁠", $ac
	kr_charmap "쁨", $ad
	kr_charmap "쁩", $ae
	kr_charmap "삐", $af
	kr_charmap "삑", $b0
	kr_charmap "삔", $b1
	kr_charmap "삘", $b2
	kr_charmap "삠", $b3
	kr_charmap "삡", $b4
	kr_charmap "삣", $b5
	kr_charmap "삥", $b6
	kr_charmap "사", $b7
	kr_charmap "삭", $b8
	kr_charmap "삯", $b9
	kr_charmap "산", $ba
	kr_charmap "삳", $bb
	kr_charmap "살", $bc
	kr_charmap "삵", $bd
	kr_charmap "삶", $be
	kr_charmap "삼", $bf
	kr_charmap "삽", $c0
	kr_charmap "삿", $c1
	kr_charmap "샀", $c2
	kr_charmap "상", $c3
	kr_charmap "샅", $c4
	kr_charmap "새", $c5
	kr_charmap "색", $c6
	kr_charmap "샌", $c7
	kr_charmap "샐", $c8
	kr_charmap "샘", $c9
	kr_charmap "샙", $ca
	kr_charmap "샛", $cb
	kr_charmap "샜", $cc
	kr_charmap "생", $cd
	kr_charmap "샤", $ce

	kr_charmap "샥", $d1
	kr_charmap "샨", $d2
	kr_charmap "샬", $d3
	kr_charmap "샴", $d4
	kr_charmap "샵", $d5
	kr_charmap "샷", $d6
	kr_charmap "샹", $d7
	kr_charmap "섀", $d8
	kr_charmap "섄", $d9
	kr_charmap "섈", $da
	kr_charmap "섐", $db
	kr_charmap "섕", $dc
	kr_charmap "서", $dd
	kr_charmap "석", $de
	kr_charmap "섞", $df
	kr_charmap "섟", $e0
	kr_charmap "선", $e1
	kr_charmap "섣", $e2
	kr_charmap "설", $e3
	kr_charmap "섦", $e4
	kr_charmap "섧", $e5
	kr_charmap "섬", $e6
	kr_charmap "섭", $e7
	kr_charmap "섯", $e8
	kr_charmap "섰", $e9
	kr_charmap "성", $ea
	kr_charmap "섶", $eb
	kr_charmap "세", $ec
	kr_charmap "섹", $ed
	kr_charmap "센", $ee
	kr_charmap "셀", $ef
	kr_charmap "셈", $f0
	kr_charmap "셉", $f1
	kr_charmap "셋", $f2
	kr_charmap "셌", $f3
	kr_charmap "셍", $f4
	kr_charmap "셔", $f5
	kr_charmap "셕", $f6
	kr_charmap "션", $f7
	kr_charmap "셜", $f8
	kr_charmap "셤", $f9
	kr_charmap "셥", $fa
	kr_charmap "셧", $fb
	kr_charmap "셨", $fc
	kr_charmap "셩", $fd
	kr_charmap "셰", $fe
	kr_charmap "셴", $ff
